/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: song16.c                                              *
* Font:        ËÎÌå                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\×ÊÁÏ\emWin\Tool5.46\3.txt                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_53E3[ 32] = { /* code 53E3 */
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6D4B[ 32] = { /* code 6D4B */
  ________,_____X__,
  __X__XXX,XX___X__,
  ___X_X__,_X___X__,
  ___X_X__,_X_X_X__,
  X____X_X,_X_X_X__,
  _X___X_X,_X_X_X__,
  _X___X_X,_X_X_X__,
  ___X_X_X,_X_X_X__,
  ___X_X_X,_X_X_X__,
  __X__X_X,_X_X_X__,
  XXX__X_X,_X_X_X__,
  __X____X,_____X__,
  __X___X_,X____X__,
  __X___X_,_X___X__,
  __X__X__,___X_X__,
  ____X___,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_7528[ 32] = { /* code 7528 */
  ________,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  _X_____X,____X___,
  _X_____X,__X_X___,
  X_______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_7A97[ 32] = { /* code 7A97 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X__X___,__X___X_,
  X__X__X_,___X_X__,
  _____X__,________,
  __XXXXXX,XXXXX___,
  __X___X_,____X___,
  __X___XX,XX__X___,
  __X__X__,_X__X___,
  __X_X_X_,X___X___,
  __X____X,____X___,
  __X___X_,X___X___,
  __X__X__,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_8BD5[ 32] = { /* code 8BD5 */
  ________,__X_X___,
  __X_____,__X__X__,
  ___X____,__X__X__,
  ___X____,__X_____,
  _____XXX,XXXXXXX_,
  ________,__X_____,
  XXXX____,__X_____,
  ___X_XXX,XXX_____,
  ___X___X,__X_____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X_X_X,___X____,
  ___XX__X,XX__X_X_,
  ___X_XXX,____X_X_,
  ______X_,_____XX_,
  ________,______X_};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsong16_CharInfo[5] = {
   {  16,  16,  2, acGUI_Fontsong16_53E3 } /* code 53E3 */
  ,{  16,  16,  2, acGUI_Fontsong16_6D4B } /* code 6D4B */
  ,{  16,  16,  2, acGUI_Fontsong16_7528 } /* code 7528 */
  ,{  16,  16,  2, acGUI_Fontsong16_7A97 } /* code 7A97 */
  ,{  16,  16,  2, acGUI_Fontsong16_8BD5 } /* code 8BD5 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop5 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop4 = {
   0x7A97 /* first character */
  ,0x7A97 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  3] /* address of first character */
  ,&GUI_Fontsong16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop3 = {
   0x7528 /* first character */
  ,0x7528 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  2] /* address of first character */
  ,&GUI_Fontsong16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop2 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_Fontsong16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontsong16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop1 = {
   0x53E3 /* first character */
  ,0x53E3 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsong16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsong16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

