/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.46                          *
*        Compiled Dec 12 2017, 16:38:40                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "include.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_GRAPH_0 (GUI_ID_USER + 0x05)
#define ID_MULTIEDIT_0 (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HWIN hGraphWin;
static GRAPH_DATA_Handle hData;    // 图表数据对象句柄
static GRAPH_SCALE_Handle hScaleV; // 垂直刻度句柄
static GRAPH_SCALE_Handle hScaleH; // 水平刻度句柄
static LISTVIEW_Handle hListView;  //  创建记录表句柄
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 1, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Status_Text", ID_TEXT_0, 598, 15, 80, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text1", ID_TEXT_1, 454, 71, 80, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text2", ID_TEXT_2, 598, 69, 80, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text3", ID_TEXT_3, 717, 75, 80, 40, 0, 0x64, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 20, 230, 431, 191, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 597, 117, 198, 357, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  uint16_t usVal;
  uint8_t ucaBuf[30];
  float_t fTemp;
  int16_t sCurrent;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00804000));
    //
    // Initialization of 'Status_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_16_ASCII);
    TEXT_SetText(hItem, "Status_Text");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    TEXT_SetFont(hItem, GUI_FONT_16_ASCII);
    TEXT_SetText(hItem, "Text1");
    //
    // Initialization of 'Text2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_16_ASCII);
    TEXT_SetText(hItem, "Text2");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_16_ASCII);
    TEXT_SetText(hItem, "Text3");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Graph'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 0, 0, 0, 0);
    // USER START (Optionally insert additional code for further widget initialization)
    GRAPH_SetGridVis(hItem, 1);
    hData = GRAPH_DATA_YT_Create(GUI_GREEN, 4096, 0, 0);
    GRAPH_AttachData(hItem, hData); //放到图表中
    // USER END
      break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_PAINT:
  {

  }

  break;
      
  case WM_TIMER:
  {
       
      //------------------------------------------------------

      // Initialization of 'Status_Text'
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
      TEXT_SetFont(hItem, &XBF_Font24);
      TEXT_SetText(hItem, "状态");

      // Initialization of 'Text1'
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
      TEXT_SetFont(hItem, &XBF_Font24);
      if (g_ucSupplyStatus == POSITIVE_POWER_SUPPLY)
      {
          TEXT_SetTextColor(hItem, GUI_GREEN);
      }
      else
      {
          TEXT_SetTextColor(hItem, GUI_WHITE);
      }
      TEXT_SetText(hItem, "正供");

      // Initialization of 'Text2'
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
      TEXT_SetFont(hItem, &XBF_Font24);
      if (g_ucSupplyStatus == STOP_SUPPLY)
      {
          TEXT_SetTextColor(hItem, GUI_GREEN);
      }
      else
      {
          TEXT_SetTextColor(hItem, GUI_WHITE);
      }
      TEXT_SetText(hItem, "停供");

      // Initialization of 'Text3'
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
      TEXT_SetFont(hItem, &XBF_Font24);
      if (g_ucSupplyStatus == NEGATIVE_POWER_SUPPLY)
      {
          TEXT_SetTextColor(hItem, GUI_GREEN);
      }
      else
      {
          TEXT_SetTextColor(hItem, GUI_WHITE);
      }
      TEXT_SetText(hItem, "负供");

      //------------------------------
      hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
      MULTIEDIT_SetFont(hItem, &XBF_Font24);
      MULTIEDIT_SetFocusable(hItem, OFF);
      MULTIEDIT_SetInsertMode(hItem, ON);
      MULTIEDIT_SetTextColor(hItem, 0, GUI_BLUE);

      MULTIEDIT_AddText(hItem, "电池信息：\n\r");

      usVal = batMode();
      sprintf((char *)ucaBuf, "模式：%X\n\r", usVal);
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      usVal = batStatus();
      sprintf((char *)ucaBuf, "状态：%X\n\r", usVal);
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      usVal = batTemperature();
      fTemp = (float)usVal / 10;
      fTemp = fTemp - 273.15;
      sprintf((char *)ucaBuf, "温度：%.2f\n\r", fTemp);
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      usVal = batVoltage();
      fTemp = (float)usVal / 1000;
      sprintf((char *)ucaBuf, "电压：%.2f", fTemp);
      strcat((char *)ucaBuf, "V\n\r");
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      sCurrent = batCurrent();
      fTemp = (float)sCurrent / 1000;
      sprintf((char *)ucaBuf, "电流：%.2f", fTemp);
      strcat((char *)ucaBuf, "A\n\r");
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      usVal = batRelativeStateOfCharge();
      sprintf((char *)ucaBuf, "相对剩余：%d", usVal);
      strcat((char *)ucaBuf, "%\n\r");
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      usVal = batAbsoluteStateOfCharge();
      sprintf((char *)ucaBuf, "绝对剩余：%d", usVal);
      strcat((char *)ucaBuf, "%\n\r");
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      usVal = batRemainingCapacity();
      fTemp = (float)usVal / 1000;
      sprintf((char *)ucaBuf, "剩余电量：%.2f", fTemp);
      strcat((char *)ucaBuf, "Ah\n\r");
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      usVal = batFullChargeCapacity();
      fTemp = (float)usVal / 1000;
      sprintf((char *)ucaBuf, "总容量：%.2f", fTemp);
      strcat((char *)ucaBuf, "Ah\n\r");
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      usVal = batChargingCurrent();
      fTemp = (float)usVal / 1000;
      sprintf((char *)ucaBuf, "充电电流：%.2f", fTemp);
      strcat((char *)ucaBuf, "A\n\r");
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      usVal = batChargingVoltage();
      fTemp = (float)usVal / 1000;
      sprintf((char *)ucaBuf, "充电电压：%.2f", fTemp);
      strcat((char *)ucaBuf, "V\n\r");
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      usVal = batSerialNumber();
      sprintf((char *)ucaBuf, "序列号：%X\n\r", usVal);
      MULTIEDIT_AddText(hItem, (char *)ucaBuf);

      g_ucSupplyStatus++;
      if (g_ucSupplyStatus > 2)
      {
          g_ucSupplyStatus = 0;
      }
      if (g_ucPulseWidth < 1)
      {
          g_ucPulseWidth = 1;
      }
      WM_RestartTimer(pMsg->Data.v, g_ucPulseWidth * 1000); //重新启动定时器
  }
  break;
      
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
